version: '3.9'

services:

  robot:
    build:
      context: .
      dockerfile: DockerfileBot
    container_name: robot
    command: >
      /bin/sh -c "
                  while ! nc -z postgres 5432; do sleep 1; done;
                  python bot.py"
    volumes:
      - ./robot:/app/robot
      - ./static:/app/static
      - ./media:/app/media
    networks:
      - shared_network
    depends_on:
      - postgres
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webadmin
    networks:
      - shared_network
    command: >
      /bin/sh -c "
                  while ! nc -z postgres 5432; do sleep 1; done;
                  python manage.py collectstatic --noinput && 
                  python manage.py migrate && 
                  gunicorn --workers ${WORKERS_COUNT} --reload --bind 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0
    container_name: botdb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge