# Generated by Django 5.2 on 2025-05-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0002_user_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
