# Generated by Django 5.2 on 2025-05-15 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CheckPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_phone', to='_auth.user')),
            ],
            options={
                'verbose_name': 'Check Phone',
                'verbose_name_plural': 'Check Phones',
                'db_table': 'check_phone',
            },
        ),
    ]
